version: '3'
services: 
  app:
    container_name: shopall
    restart: always
    build: .
    links: 
      - shopalldb
    volumes: 
      - store:/usr/src/app/public/uploads
      - node_modules:/usr/src/app/node_modules
    networks:
      net:
        ipv4_address: ${IP_PREFIX}.2
    ports: 
      - '5000'
    environment: 
      - DB_PATH=shopalldb
  shopalldb:
    container_name: shopalldb
    image: mongo
    volumes: 
      - db:/data/db
    networks: 
      net:
        ipv4_address: ${IP_PREFIX}.3
    ports:
      - '27017'
networks: 
    net:
      ipam:
        driver: default
        config:
            - subnet: ${IP_PREFIX}.0/16
volumes: 
  db:
  store:
  node_modules:
